### ISSUE TITLE
Hitch doesn't appear to be working

### ISSUE THREAD

**Issue by caraya** [bkardell/Hitch#34]
I'm working on chrome 50 and am having issues getting Hitch to work. 

I've created a demo (https://gist.github.com/caraya/8517dcd1bb03da371f19aaffc5aa3cb1) and, as far as I understand Hitch it should be working but it's not.  I've followed the quick start guide and I've looked at the other demos. 

Can someonne help me figure out what's wrong with it?

I'm using hitch 0.6.3

Thanks

**Comment by bkardell** [comment]
You can diff your gist with this one..
https://gist.githubusercontent.com/bkardell/5e6711240d0213e978a1a115508745d1/raw/6b0393a1e9580d121281d7e962af223348f24b4d/hitch-demo.html

Key points: 
  1) be sure http/https is good (if you're serving off https,  you should load off https).

  2) @-hitch-requires is really stupid, only one space between that and the url or it won't work :(  Not just it won't work, much worse actually because it will get thrown away like an invalid CSS rule and nothing will try to require/import.

  3) be sure that the thing you are requiring exists by checking the url.  in your case it was missing /use/ in the path. All the custom pseudo classes hosted on hitch that you can import include /use/ in the url and you can swap the /use/ with /describe/ to get the documentation for it ala https://www.hitchjs.com/use/bkardell.math/1 and https://www.hitchjs.com/describe/bkardell.math/1

See the updated gist running here, let me know if it doesn't work or you are having problems with that one.
https://rawgit.com/bkardell/5e6711240d0213e978a1a115508745d1/raw/6b0393a1e9580d121281d7e962af223348f24b4d/hitch-demo.html

**Comment by caraya** [comment]
Got it. The example is now working 👍
