### ISSUE TITLE
Add comment support for CSS source in compiler

### ISSUE THREAD

**Issue by clintjhill** [bkardell/Hitch#9]
Currently if there are commented rules within the CSS source - the compiler will 'process' the rules within comments.

Specifically if there are commented @-plugins-require or @-plugins-const they will be processed and cause inconsistencies and strange results for the native CSS.

**Comment by bkardell** [comment]
Hmm...@ rules specifically could be problematic, others would probably be debatable or at least very low in the priorites... Luckily all of the @ rules we can currently deal with are 1 liners and all @ rules come before regular rules so we can probably add an exclusion to the regex.  Since these are specifically not listed in the filters list, they should be left alone otherwise.

**Comment by clintjhill** [comment]
To be clear - the case I ran across was commenting out an @-plugin-require rule and it continued to process/request the source. @-plugin-const will do the same, which is if I comment it out, it will still do replacements throughout the rules.

We need to exclude all(?) comments on the input we use to process/compile these rules.

**Comment by clintjhill** [comment]
There is now a helper function for trimming - possibly that can be used early in the compiler?
